name: secret

on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY_1: ${{ secrets.GEMINI_API_KEY_1 }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set API to ENV
        run: echo "GEMINI_API_KEY_1=$GEMINI_API_KEY_1" >> $GITHUB_ENV